=== IooGoZ/ProjetJavaL3S5/src/fr/LNT/storymaker/kernel/utils/xml/game.dtd
<!--Game-->
<!ELEMENT game 
    (script, map, items-list, characters-list)
>
<!ATTLIST game 
    name CDATA #REQUIRED
>


<!--Script-->
<!ELEMENT script 
    (script-node+)
>
<!ATTLIST script 
    begin CDATA #REQUIRED
>

<!ELEMENT script-node 
    (child*)
>
<!ATTLIST script-node  
    id ID #REQUIRED
>

<!ELEMENT child EMPTY>
<!ATTLIST child 
    child-id IDREF #REQUIRED
>


<!--Map-->
<!ELEMENT map 
    (location+)
>
<!ATTLIST map 
    begin CDATA #REQUIRED
>

<!ELEMENT location 
    (name, text*, desc, door*)
>
<!ATTLIST location 
    id ID #REQUIRED
>

<!ELEMENT door EMPTY>
<!ATTLIST door 
    id ID #REQUIRED
    to CDATA #REQUIRED
    key CDATA #IMPLIED
>


<!--Items List-->
<!ELEMENT items-list
 (item*)
>

<!ELEMENT item
 (name, desc)
>
<!ATTLIST item 
    id ID #REQUIRED
>


<!--Characters list-->
<!ELEMENT characters-list
    (character*)
>

<!ELEMENT character 
    (name, desc, dialog*)
>
<!ATTLIST character 
    id ID #REQUIRED
    location CDATA #REQUIRED
    available IDREFS #IMPLIED
>

<!--Dialog-->
<!ELEMENT dialog
    (dialog-node*)
>
<!ATTLIST dialog 
    id ID #REQUIRED
    begin CDATA #REQUIRED
    available IDREFS #IMPLIED
>

<!ELEMENT dialog-node
    (text, answer*)
>
<!ATTLIST dialog-node 
    id ID #REQUIRED
    execute CDATA #IMPLIED
>

<!ELEMENT answer
    (#PCDATA)
>
<!ATTLIST answer 
    redirect IDREF #IMPLIED
>


<!--Global-->
<!ELEMENT name
    (#PCDATA)
>

<!ELEMENT desc
    (#PCDATA)
>

<!ELEMENT text
    (#PCDATA)
>

=== IooGoZ/ProjetJavaL3S5/src/fr/LNT/storymaker/kernel/utils/xml/dialog_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "game.dtd">
<dialog id="test-dialog" begin="test1">
    <dialog-node id="test1">
        <text>Bonjour, ça va ?</text>
        <answer redirect="test2">ça va !</answer>
        <answer redirect="test3">Bah non...</answer>
    </dialog-node>
    <dialog-node id="test2">
        <text>Cool ! c'est bien ça !</text>
        <answer redirect="test4">Effectivement</answer>
        <answer redirect="test3">Bah non...</answer>
    </dialog-node>
    <dialog-node id="test3">
        <text>Il faut être joyeux dans la vie !</text>
        <answer redirect="test4">C'est vrai !</answer>
        <answer redirect="test2">Bah non...</answer>
    </dialog-node>
    <dialog-node id="test4">
        <text>Bah c'est bien...</text>
        <answer>Oui...</answer>
    </dialog-node>
</dialog>

=== IooGoZ/ProjetJavaL3S5/src/fr/LNT/storymaker/kernel/utils/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE game SYSTEM "game.dtd">
<game name="Test adventure">
    <script begin="sc-1">
        <script-node id="sc-1">
            <child child-id="sc-2"/>
            <child child-id="sc-4"/>
        </script-node>
        <script-node id="sc-2">
            <child child-id="sc-1"/>
            <child child-id="sc-3"/>
            <child child-id="sc-4"/>
        </script-node>
        <script-node id="sc-3">
            <child child-id="sc-2"/>
            <child child-id="sc-1"/>
        </script-node>
        <script-node id="sc-4">
            <child child-id="sc-1"/>
            <child child-id="sc-2"/>
            <child child-id="sc-3"/>
        </script-node>
    </script>
    <map begin="loc1">
        <location id="loc1">
            <name></name>
            <desc></desc>
            <door id="door1" to="loc1"/>
        </location>
    </map>
    <items-list>
        <item id="key">
            <name></name>
            <desc></desc>
        </item>
    </items-list>
    <characters-list>
        <character id="Maria" location="">
            <name></name>
            <desc></desc>
            <dialog id="mar_dia_1" begin="test1">
                <dialog-node id="test1">
                    <text>Bonjour, ça va ?</text>
                    <answer redirect="test2">ça va !</answer>
                    <answer redirect="test3">Bah non...</answer>
                </dialog-node>
                <dialog-node id="test2">
                    <text>Cool ! c'est bien ça !</text>
                    <answer redirect="test4">Effectivement</answer>
                    <answer redirect="test3">Bah non...</answer>
                </dialog-node>
                <dialog-node id="test3">
                    <text>Il faut être joyeux dans la vie !</text>
                    <answer redirect="test4">C'est vrai !</answer>
                    <answer redirect="test2">Bah non...</answer>
                </dialog-node>
                <dialog-node id="test4">
                    <text>Bah c'est bien...</text>
                    <answer>Oui...</answer>
                </dialog-node>
            </dialog>
        </character>
    </characters-list>
</game>
